config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('account/', include('allauth.urls')),
]

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('diary/create/', views.DiaryCreateView.as_view(), name='diary_create'),
    path('diary/create/complete/', views.DiaryCreateCompleteView.as_view(), name='diary_create_complete'),
    path('diary/list/', views.DiaryListView.as_view(), name='diary_list'),
    path('diary/detail/<uuid:pk>/', views.DiaryDetailView.as_view(), name='diary_detail'),
    path('diary/update/<uuid:pk>/', views.DiaryUpdateView.as_view(), name='diary_update'),
    path('diary/delete/<uuid:pk>/', views.DiaryDeleteView.as_view(), name='diary_delete'),
]

accounts/models.py
from django.contrib.auth.models import UserManager, AbstractUser

class CustomUserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, username, password, **extra_fields):
        # create_user と create_superuser の共通処理
        if not email:
            raise ValueError('email must be set')
        if not username:
            raise ValueError('username must be set')

        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, username, email=None, password=None, **extra_fields):

        if not email:
            raise ValueError('email must be set')
        if not username:
            raise ValueError('username must be set')

        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)

        return self._create_user(email, username, password, **extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, username, password, **extra_fields)

class CustomUser(AbstractUser):
    objects = CustomUserManager()

    def __str__(self):
        return self.email

diary/models.py
from django.db import models
from django.utils import timezone
import uuid


class Diary(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(verbose_name='日付', default=timezone.now)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    text = models.CharField(verbose_name='本文', max_length=200)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)

diary/forms.py
from django import forms
from .models import Diary


class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('date', 'title', 'text')
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.TextInput(attrs={'class': 'form-control'}),
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

diary/views.py
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils import timezone
from .forms import DiaryForm
from .models import Diary

class IndexView(TemplateView):
    template_name = 'index.html'

class DiaryCreateView(CreateView):
    template_name = 'diary_create.html'
    form_class = DiaryForm
    success_url = reverse_lazy('diary:diary_create_complete')

class DiaryCreateCompleteView(TemplateView):
    template_name = 'diary_create_complete.html'

class DiaryListView(ListView):
    template_name = 'diary_list.html'
    model = Diary

class DiaryDetailView(DetailView):
    template_name = 'diary_detail.html'
    model = Diary

class DiaryUpdateView(UpdateView):
    template_name = 'diary_update.html'
    model = Diary
    fields = ('date', 'title', 'text',)
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.updated_at = timezone.now()
        diary.save()
        return super().form_valid(form)

class DiaryDeleteView(DeleteView):
    template_name = 'diary_delete.html'
    model = Diary
    success_url = reverse_lazy('diary:diary_list')

templates/base.html
<!DOCTYPE html>
<html lang="jp">
{% bootstrap_css %}
<head>
    <meta charset="UTF-8">
    <title>MyDjangoApp</title>
</head>
<body>
<a href="{% url 'account_logout' %}">ログアウト</a>
{% block content %}
{% endblock %}
</body>
</html>

templates/diary_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <h1>日記の作成</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>{{ form.date.label }}</label>
            {{ form.date | add_class:'form-control col-2' }}
        </div>
        <div class="form-group">
            <label>{{ form.title.label }}</label>
            {{ form.title | add_class:'form-control col-2' }}
        </div>
        <div class="form-group">
            <label>{{ form.text.label }}</label>
            {{ form.text | add_class:'form-control col-2' }}
        </div>
        <button type="submit" class="form-control col-1">投稿</button>
    </form>
{% endblock %}

templates/diary_create_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyDiaryApp</title>
</head>
<body>
<p>日記の投稿が完了しました！</p>
<a href="{% url 'diary:index' %}">トップへ戻る</a>
</body>
</html>

templates/diary_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>日記の削除</h1>
<form method="post">
    {% csrf_token %}
    <p>{{ diary.date }} {{ diary.title }} を削除します</p>
    <input type="submit" value="削除">
</form>
</body>
</html>

templates/diary_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>{{ diary.date }}</p>
<p>{{ diary.title }}</p>
<p>{{ diary.text }}</p>
<a href="{% url 'diary:diary_update' diary.pk %}">編集</a>
<a href="{% url 'diary:diary_delete' diary.pk %}">削除</a>
<a href="{% url 'diary:index' %}">戻る</a>
</body>
</html>

templates/diary_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for diary in diary_list %}
<p>
    {{ diary.date }}
    <a href="{% url 'diary:diary_detail' diary.pk %}">{{ diary.title }}</a>
</p>
{% endfor %}
<a href="{% url 'diary:index' %}">戻る</a>
</body>
</html>

templates/diary_update.html
{% extends 'base.html' %}
{% block content %}
<h1>日記の編集</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存">
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Diary App by Django</h1>
<h2><a href="{% url 'diary:diary_create' %}">日記の投稿</a></h2>
<h2><a href="{% url 'diary:diary_list' %}">日記の一覧</a></h2>
{% endblock %}